### ISSUE TITLE
freezes steam.

### ISSUE THREAD

**Issue by ocewot** [b1gnout/VAC-Bypass#1]
says hooks successful but i cant type in my password or anything steam is just frozen? am i supposed to do this after logging in?

**Comment by b1gnout** [comment]
Yes, you should inject after logging in and before you start your game. Steam may have some visual glitches but you will be able to start games like normal.

**Comment by ocewot** [comment]
> Yes, you should inject after logging in and before you start your game. Steam may have some visual glitches but you will be able to start games like normal.

thank you for your response i figured it out later :) yeah it works well i was just confused having used a different vac bypass previously. also idk if im just dumb but i joined the discord and reacted to the rules but im stuck without a role. my username is ocew
