### ISSUE TITLE
Steam quit by himself

### ISSUE THREAD

**Issue by jackKiZhu** [b1gnout/VAC-Bypass#10]
When playing csgo, steam will quit by itself. Then the game will exit.

**Comment by b1gnout** [comment]
Hi, please make sure you have ran steam as administrator.

**Comment by jackKiZhu** [comment]
> Hi, please make sure you have ran steam as administrator.

I run as an administrator. If I don't run as an administrator, I can't inject.

**Comment by DLdota** [comment]
+1 sometimes steam crashes, i think its a problem with GameOverlayUi.exe
i tried to disable game overay, but anyway got the same crash : 

![image](https://user-images.githubusercontent.com/10529536/179086089-0facb3ad-9ee1-4372-a81b-0d7a55d806f4.png)
![image](https://user-images.githubusercontent.com/10529536/179086137-ec75bc81-02ab-4adf-987d-dd90b75fdfe3.png)

**Comment by DLdota** [comment]
Up!
after some research, im sure this random crash heppend when the VirtualQuerty hook got lpAdress from steamservice.dll
![image](https://user-images.githubusercontent.com/10529536/182051355-b894b6c3-e06e-4486-96bd-9d6e501d1eeb.png)

**Comment by anfogy** [comment]
plz close this issue
