### ISSUE TITLE
How do i write my own injector for this bypass? 

### ISSUE THREAD

**Issue by mastercodeon314** [b1gnout/VAC-Bypass#14]
Can i get some help writing my own injector for this bypass?

**Comment by dgrfps** [comment]
Just google it.
https://www.apriorit.com/dev-blog/679-windows-dll-injection-for-api-hooks
https://www.google.com/search?q=CreateRemoteThread
https://guidedhacking.com/threads/c-manual-map-injection.58/

**Comment by anfogy** [comment]
please close this issue if you won’t have any deeper discussion again.
