### ISSUE TITLE
Does it still work?

### ISSUE THREAD

**Issue by DryreL** [b1gnout/VAC-Bypass#15]
Hi,

I tried to inject with [Broihon](https://github.com/Broihon) / [GH-Injector-GUI](https://github.com/Broihon/GH-Injector-GUI) but it seems I'm still VAC banned and cannot play on VAC-secure servers. I started Steam.exe as admin. Any idea or solution?

![image](https://user-images.githubusercontent.com/20909077/184136503-7dcad065-b6a9-4d8c-b53e-b5d43c69bd6d.png)

**Comment by dgrfps** [comment]
Yes it still working, should try using Manual map.
It wont unban you, it isnt its purpose.

**Comment by DryreL** [comment]
> Yes it still working, should try using Manual map. It wont unban you, it isnt its purpose.

Thanks for quick reply! Yes, I used Manual Mapping but it didn't work as you can see in the screenshot. I know it won't unban the account but I cannot connect VAC secure servers either.

Maybe there is a problem with the injector. Can you recommend a different injector?

**Comment by dgrfps** [comment]
https://www.unknowncheats.me/forum/general-programming-and-reversing/213038-extreme-injector-v3-7-a.html

I dont think i will make you able to connect to vac secured servers, vac record is on your account details, the server backends isn't processed by Steam.exe (Process that you're injecting the bypass), I.e. Server will check your acc info, it doesn't matter if you disabled vac modules

**Comment by DryreL** [comment]
I got it now. We need to use this DLL when there is no VAC ban on the account. 

I thought it allowed us to connect to the VAC-secure server even though it didn't remove the existing VAC ban history
