### ISSUE TITLE
Questions 

### ISSUE THREAD

**Issue by aldias14** [b1gnout/VAC-Bypass#16]
How can I contact for developer? Have you got telegram/discord? I want to ask many questions about this bypass and it will be better and faster if you give me your contacts please. Regards.

**Comment by dgrfps** [comment]
I ain't this project developer, but i'll answer as possible based on my knowledge. Meanwhile the manufacturer doesn't reply, post your questions here so me and/or other devs can reply, it also may be helpful to other people with the same questions.

**Comment by aldias14** [comment]
Are all signatures and addresses updated to the current version at the moment?
Was at least one account blocked? If so, is there a certain delay before vac ban? For example 1,2,3 months.

**Comment by aldias14** [comment]
Does it affect the trust factor?

**Comment by dgrfps** [comment]
About ban delays, when I've played CSGO, vac were made in waves. Read this thread on steam forum.
Also it is almost impossible to determinate if is the bypass detected or an cheat dll detected.

About signatures i aint sure, probably is updated. 

https://steamcommunity.com/discussions/forum/9/3094515496014635994/

**Comment by aldias14** [comment]
What about trust factor?

**Comment by aldias14** [comment]
If I inject this dll into the steam too fast it says that unable to find steamservice.dll. But if i will wait about 5-10 seconds all be ok. I'm trying to make loader for this bypass to inject needed to me dll automatically. How can I check when steamservice.dll loaded and in summary when I must inject it? Also I run with admin rights

**Comment by dgrfps** [comment]
try this https://docs.microsoft.com/en-us/windows/win32/api/psapi/nf-psapi-getmoduleinformation

```cpp
do 
{
sleep(10ms);
}
while(!dll-found);

//inject here
```

**Comment by aldias14** [comment]
I wrote this func instead and ye it works fine. But does steam check/detect GetModuleBaseAddress() function which code is below. Is it safe to use it before patching vac?

`BOOL GetModuleBaseAddress(DWORD procId, const char* modName)
{
	uintptr_t modBaseAddr = 0;
	HANDLE hSnap = CreateToolhelp32Snapshot(TH32CS_SNAPMODULE | TH32CS_SNAPMODULE32, procId);
	if (hSnap != INVALID_HANDLE_VALUE)
	{
		MODULEENTRY32 modEntry;
		modEntry.dwSize = sizeof(modEntry);
		if (Module32First(hSnap, &modEntry))
		{
			do
			{
				if (!_stricmp(modEntry.szModule, modName))
				{
					CloseHandle(hSnap);
					return TRUE;
				}
			} while (Module32Next(hSnap, &modEntry));
		}
	}
	CloseHandle(hSnap);
	return FALSE;
}`

**Comment by MrCowboy20** [comment]
@dgrfps Plz help :
does this effect red trust factor?

Thanks

**Comment by dgrfps** [comment]
no idea

**Comment by b1gnout** [comment]
Closing this as not directly related to this repo, you can contact me on https://t.me/Bignout
