### ISSUE TITLE
isnt issue but ye

### ISSUE THREAD

**Issue by certifiedsw4gger** [b1gnout/VAC-Bypass#3]
just a question is this vac bypass giving red trust factor like vac bypass by daniel or the one used in csghost injector?

**Comment by b1gnout** [comment]
> just a question is this vac bypass giving red trust factor like vac bypass by daniel or the one used in csghost injector?
> 
> 

No, from my testing and what other people have said, it will not affect trust factor. Make sure your using it properly.

**Comment by certifiedsw4gger** [comment]
> > just a question is this vac bypass giving red trust factor like vac bypass by daniel or the one used in csghost injector?
> 
> No, from my testing and what other people have said, it will not affect trust factor. Make sure your using it properly.

ok ty
