### ISSUE TITLE
VAC detects hooking winapi functions

### ISSUE THREAD

**Issue by Metaphysical1** [b1gnout/VAC-Bypass#5]
as the title says, vac detects jmps in winapi functions, so hooking them is not safe

**Comment by b1gnout** [comment]
Yes but this isn't a worry. The pattern scan hooks prevent this from happening.

**Comment by Metaphysical1** [comment]
> Yes but this isn't a worry. The pattern scan hooks prevent this from happening.

which function ? because all hooked functions have ambiguous names, or do you mean the memory reading function? readprocessmemory and such ?
anyway thanks for making this public.
