### ISSUE TITLE
Steam only closes itself.

### ISSUE THREAD

**Issue by issue1337** [b1gnout/VAC-Bypass#8]
Hello, I injected the dll into steam.exe but Steam just ends its whole tree process and nothing else happens.

**Comment by b1gnout** [comment]
> Hello, I injected the dll into steam.exe but Steam just ends its whole tree process and nothing else happens.

Try use our injector at: https://discord.gg/fNhyw6kYAG

**Comment by issue1337** [comment]
> > Hello, I injected the dll into steam.exe but Steam just ends its whole tree process and nothing else happens.
> 
> Try use our injector at: https://discord.gg/fNhyw6kYAG

Thanks.
